### ISSUE TITLE
More fields from Github Query should be logged into the Database

### ISSUE THREAD

**Issue by daveytech** [OpenTree-Education/rhizone-lms#355]
## Expected behaviour

From the github query when user's sign up for an account, there should also be saved fields to be used for the Profile page.

Fields to include:
- Name
- Email
- Github Link
- Github Avatar
- BIO

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by Nazanin-Rezaei** [comment]
Update on passing the GitHub user data from the router file to the service function. Next, we will insert GitHub user data into the user table.

**Comment by seidior** [comment]
If you're just joining the branch, we've got some action items for you:

- You'll need to reset your database because some migrations have been edited. Before getting your local development environment going on this branch, make sure to do a `docker-compose down` to remove the MySQL container.
- You'll need to rebuild everything with a `docker-compose build`.
- Finally, there's a new endpoint for you, `/profile/:principal_id`.

Here's today's progress on this ticket:

- The day started out with a route called `/current-user` that ostensibly had the relevant profile information being returned from the API for the current user.
  - However, that approach isn't scalable, since we'd want to show profile info for not-logged-in users. I removed and modified this endpoint.
- We created an endpoint for `/profile/:principal_id` that contains all the information needed for the folks working on #356 to link the profile page with the database, at least for reading. This includes a user's full name, bio, email address, GitHub information, and social profiles.

To use this, just call the API with endpoint `/profile/1` (for example, for principal ID (aka user ID) 1. This will show you enough information for that user for the web app to be able to render a profile page.

For those doing that work, please note:

- There are top-level `full_name` and `bio` fields that are separate from the fields given to us from GitHub; this is to allow for asynchronous changes of this information between Rhizone and GitHub. In theory the logic should work like this: if the top-level fields are null, show the information from GitHub; otherwise, show the information from Rhizone, since that's what the user has set.
- `github_accounts` and `social_networks` are both arrays. It's fair to assume they are arrays with at least one member, since currently the only way to log in is via GitHub, which populates both arrays.
- You're going to get a URL back from `social_profiles` that will look something like `//example.com/subfolder`. This is intentional. Please use this as your href; you do not need to prepend "http:" or "https:" to this.
- I've made life a little easier and pulled out the models I created into their own separate file in the `api/src/models` directory. You should assume that if data is being returned from this new endpoint, it will adhere to the models defined in this directory.

There's still a good amount of work to do, however:

- I commented out some tests in order to get the code working, but that needs to be un-done and proper testing needs to occur with the modified code.
- Not sure if it's in scope for this ticket, #355, or for the other ticket, #356, but the POST request to that endpoint needs to be handled so that the information can be updated.
- I'd love for the relevant columns in `principals` to be pre-populated with the information we get from GitHub upon first login.
- There's probably some better Express.js-native error handling that could have been done here.
- More TSDoc-style comments would be nice.
- I make no warranty for the code I added today. I tried my best to adhere to good standards, but we're running up against a deadline and things just need to work. We're now at a point where both teams can work independently on finishing their tickets.
- Look for anything else I marked with a `// TODO:` that may need some work.

This leaves the following questions:

- Is handling the POST for the edited data within scope for this ticket or the other one? If it's not in scope for this ticket, can we go ahead and merge this into main right now so as not to hold up the other team?
- Should the branch for the other ticket go ahead and pull from this one, even though it's not merged into main yet?
