### ISSUE TITLE
Add Sass Support to Webapp

### ISSUE THREAD

**Issue by seidior** [OpenTree-Education/rhizone-lms#364]
## Description

It would be rad if we added Sass support to the React-based webapp. This minor change will allow us to perform more advanced tasks than the basic CSS alone would allow us to do.

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

**Comment by seidior** [comment]
It has been determined that the project would not benefit from this addition, so I'm closing this issue.

**Comment by davidvandusen** [comment]
Here's a bit more context.

Rhizone uses [Material UI](https://mui.com/) and there are patterns for customizing MUI, for example, using `sx` props, and themes. MUI is implemented with [Styled Components](https://emotion.sh/docs/styled), which is included as a dependency, so that if new widgets need to be defined (which is unlikely), they should be defined as styled components. The syntax for styled components is similar to Sass.

Global styles may be added using the [`<GlobalStyles>`](https://mui.com/material-ui/api/global-styles/) component, but its use will be very rare. It's an option to remove the `index.css` file and replace it with `<GlobalStyles>` which could be an improvement in consistency, since the project would then have zero CSS files.
