### ISSUE TITLE
Example assignment, quiz, and test frontend template needs to be created for assessments feature

### ISSUE THREAD

**Issue by seidior** [OpenTree-Education/rhizone-lms#514]
### Describe the Feature / Enhancement

Now that we have the list of assessments on the frontend, we need the example design for what taking an assessment should look like. The specifics of implementation:

- It should work for assessments of type assignment, quiz, and test.
- It should display a timer, if applicable, and hide this timer upon user request.
- It should display questions of type single-choice as well as free response. If the list of single-choice options is greater than 5, let's display a dropdown instead.
- Submitting should request user confirmation. User confirmation should also warn if any of the questions were not answered.
- There should be a submission confirmation page after submitting that confirms the submission was received and displays the list of questions and answers again with the user's submitted answers, but with all form elements disabled.

### Correct Project Selected

- [X] This issue is linked to the appropriate project

### Labels

- [X] This issue has appropriate labels.

**Comment by zeeeeli** [comment]
EOD update: we have created one assessment with questions list based on the database migration. Add a new route to show the assessment details page, which serves as the main assessment template. The route passes assessment id as parameter. The page is empty.

**Comment by zeeeeli** [comment]
EOD update: we have created a template for the questions page, including assessment meta data for left panel and questions on the right panel. Some cool design idea for timer and progress. Layout for question card component. 

Need to fill in the logic and more meta data in to the page

**Comment by zeeeeli** [comment]
EOD update: 
- Fixed the radio button could not be uniquely selected.
- Added the dialogue after submission. 
- Calculate the total number of the answered question so we can show on the "Progress" bar and confirmation dialog.

**Comment by zeeeeli** [comment]
EOD Update: more design tweaks from spencer's feedback.
- Make the main question scrollable, with a light grey background color to make the question card standout
- Add another right section for current progress:
    - individual question status circle with a number on it
    - submit button 

![image](https://user-images.githubusercontent.com/22227133/222854830-c6a9dff5-3a31-474c-818a-b9b1185a4f38.png)

**Comment by seidior** [comment]
Hi team! Great work so far, and thanks for the screenshot and building out that feature based on my request.

Over the weekend, I made a couple of small refinements, and I wired up the countdown timer, although it still needs logic for not counting below zero as well as what to do when the timer reaches zero. (Also, logic to set the end time for the timer to either the due date or the (`startTime` + `timeLimit`), if a time limit is specified. And maybe some logic that shows days until a certain point, hours until a certain point, hours and minutes until a certain point, minutes until a certain point, minutes and seconds until a certain point, and seconds until a certain point.)

I've got some further refinements for you to consider:
- `AssessmentsDetailPage.tsx` is starting to get gnarly and long. I'd love for you to consider breaking it into different components, a la `ProgramsPage.tsx`. This will help improve readability and allow for better iterative development.
- In a couple of places, you use variable names like `open`, and `checked`. These variable names aren't clear as to what they do. Besides just documentation, proper variable and function names help to document functionality and make it easier for other developers to maintain your code in the future.
- I'd like you to reconsider your layout for this page. Perhaps a grid-based approach rather than a container-based approach may be more applicable in this case. Plus it would give you the flexibility to take a three-column-based layout and adapt it to two columns or one column based on screen width. Right now this page is... not readable on smaller screens.
- I'd prefer if the submit button only showed in the third column. Also, what do you think about this: show the submit button as the outline version until you answer all the questions, at which point we can switch to the filled-in version of the submit button?
- The switch governing the showing of the timer should be better-labeled as to what it should do, and it should have a better-designed off state.
- The questions should be displayed in a custom component, something like `AssessmentDisplay.tsx`, that could govern that whole center section.
- I like the background, but maybe let's consider a border on the outside of the assessment display?
- Instead of having a bunch of `assessment?` everywhere, maybe let's have a catch-all state for when an assessment isn't found, displaying a fallback message instead of the whole interface.
- Let's merge the progress bar with the third column instead of having it in the first.

Let me know what you think!

**Comment by kaiyolau** [comment]
EOD Update: some tweaks from spencer's feedback.

Added responsive layout style into the component of assessment.Showing meta information, list of question and the progress completion in display of block if it's mobile user.

Moved the submit button to the top of the question list.

**Comment by zeeeeli** [comment]
- [x]  `AssessmentsDetailPage.tsx` is starting to get gnarly and long. I'd love for you to consider breaking it into different components, a la `ProgramsPage.tsx`. This will help improve readability and allow for better iterative development.
- [x]  In a couple of places, you use variable names like `open`, and `checked`. These variable names aren't clear as to what they do. Besides just documentation, proper variable and function names help to document functionality and make it easier for other developers to maintain your code in the future.
- [x]  I'd like you to reconsider your layout for this page. Perhaps a grid-based approach rather than a container-based approach may be more applicable in this case. Plus it would give you the flexibility to take a three-column-based layout and adapt it to two columns or one column based on screen width. Right now this page is... not readable on smaller screens.
- [x]  I'd prefer if the submit button only showed in the third column. Also, what do you think about this: show the submit button as the outline version until you answer all the questions, at which point we can switch to the filled-in version of the submit button?
- [x]  The switch governing the showing of the timer should be better-labeled as to what it should do, and it should have a better-designed off state.
- [x]  The questions should be displayed in a custom component, something like `AssessmentDisplay.tsx`, that could govern that whole center section.
- [x]  I like the background, but maybe let's consider a border on the outside of the assessment display?
- [x]  Instead of having a bunch of `assessment?` everywhere, maybe let's have a catch-all state for when an assessment isn't found, displaying a fallback message instead of the whole interface.
- [x]  Let's merge the progress bar with the third column instead of having it in the first.

> 
> Let me know what you think!

We addressed some of the suggestion, we will continue working on the rest of them. I will commit to address some of them today.

One comment about the timer, I add a `Tooltip` on the timer switch after trying few options in the text. The hover to show `hide/show timer` seems to be the most neat/clean option. 
![image](https://user-images.githubusercontent.com/22227133/223784173-60248050-65fa-49c0-b17a-f205b4c2ae10.png)

**Comment by zeeeeli** [comment]
There are some layout changes of the left meta data column based on the status of the submission and assessment. Pasting some screenshot here for reference. 

For submitted assessment
![image](https://user-images.githubusercontent.com/22227133/223786100-317a1da7-9fc0-4319-8b9d-4e00119edd10.png)

For a active on-going test
![image](https://user-images.githubusercontent.com/22227133/223785483-8d3a0c27-b7a3-40a1-9c5b-511df36de199.png)

For a active on-going assignment 
![image](https://user-images.githubusercontent.com/22227133/223786545-611f3ca2-b80b-4212-bf84-f0848afc92fd.png)

For expired assessment 
![image](https://user-images.githubusercontent.com/22227133/223786619-035199e6-0a84-4e89-9d76-1a7cb9ab056f.png)

For graded assessment 
![image](https://user-images.githubusercontent.com/22227133/223786780-da610d6b-5c73-4fee-a0d6-6d536fbe4990.png)

**Comment by zeeeeli** [comment]
Also some looks with colored icon
![image](https://user-images.githubusercontent.com/22227133/223789347-24447322-7447-4d56-a2f5-f69601cf3186.png)
![image](https://user-images.githubusercontent.com/22227133/223789437-fb482f3e-b3b1-40f1-bc37-e1b035b6cd5f.png)

**Comment by zeeeeli** [comment]
EOD (late) update, apart from addressing issues from previous comments, including:

- Break the detail page into 3 sub components for better readability and maintaining the code 
- Add confirmation alert after submission
- Show different metadata on the left based on the assessment type, submission states
   - Change icon to single colored, and only colored when taking the assessment

Next, warp up remaining one comment and ready for PR

**Comment by seidior** [comment]
EOD Update:

@ZeyuanLi16 worked on addressing my PR comments through ticket #540, then merged that in with this branch when he was done addressing those comments.

This evening, I restructured some of the component code based around example data that better fits the format of the data that we'll be retrieving from the database, minimizing the amount of work that would need to be done to ready this component to link up to the backend.

Also, I further refactored the code around using React state variables, which better matches the behavior we would expect from a network-dependent component like this.

Finally, there were some minor visual tweaks to answer some open questions Ze had about applying CSS styles using styled-components-like syntax.

The remaining steps, should anyone choose to tackle them:
- I think we lost the two-column layout along the way (or did we have it at one point?), so that may be a welcome addition.
- Any further visual refinements that should be done to jazz up this component before signing off on it for now.
- There's a TODO task on L71 of `AssessmentDetailPage.tsx` for an optional task to tackle. Otherwise we can leave that comment for the next person to work on this component.
- Screenshots need to be updated in the pull request.

All in all, minor tasks remaining, with the lion's share of the work in the past 24 hours having been completed by Ze. This component has really shaped up over the weeks and everyone contributing to this branch should be really proud of the end result!
